### ISSUE TITLE
Error with roam-importable-year

### ISSUE THREAD

**Issue by anthrolisp** [jjthrash/roam-tools#2]
ruby roam-importable-year 2021 > 2021.json

outputs the following error:

Traceback (most recent call last):
	2: from roam-importable-year:3:in `<main>'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- pry (LoadError)

Any thoughts? Thanks in advance!

**Comment by jjthrash** [comment]
@anthrolisp I had left a debug tool in place. It's gone now. Give it a try again!

**Comment by anthrolisp** [comment]
It works, thank you!!!!
