### ISSUE TITLE
Monday :)

### ISSUE THREAD

**Issue by tombarys** [jjthrash/roam-tools#5]
Hi, this is really great. How to make the week start with Monday? Is that possible? Thank you!

**Comment by jjthrash** [comment]
> Hi, this is really great. How to make the week start with Monday? Is that possible? Thank you!

Here you go: https://github.com/jjthrash/roam-tools/releases/tag/2024.2

**Comment by tombarys** [comment]
Thanks, that is really great! I will share with RoamResearch users and friends!
